=== owlytest/OwlyServer/OwlySrv/src/main/resources/properties/OwlySrv.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<xs:simpleType name="IP">
		<xs:restriction base="xs:string">
			<xs:pattern value="[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ServerType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="LoadServer"/>
			<xs:enumeration value="AdminServer"/>
			<xs:enumeration value="SubsServer"/>
			<xs:enumeration value="JMSServer"/>
			<xs:enumeration value="DatabaseServer"/>
			<xs:enumeration value="ApacheServer"/>
			<xs:enumeration value="DimServer"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AnalyzeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="SingleHost"/>
			<xs:enumeration value="MultiHost"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="StatType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Stats_Vmstat"/>
			<xs:enumeration value="Stats_TopCPU"/>
			<xs:enumeration value="Stats_IdleCPU"/>
			<xs:enumeration value="Stats_VmRSS"/>
			<xs:enumeration value="Stats_SwapKB"/>
			<xs:enumeration value="Stats_Top10VmRSS"/>
			<xs:enumeration value="Stats_Top10CPU"/>
			<xs:enumeration value="Stats_AllBytesxsec"/>
			<xs:enumeration value="Stats_Bytesxsec"/>
			<xs:enumeration value="Stats_MaxBusyIO"/>
			<xs:enumeration value="Stats_Multi_BusyIO"/>
			<xs:enumeration value="Stats_Multi_Bytesxsec"/>
			<xs:enumeration value="Stats_Multi_VmRSS"/>
			<xs:enumeration value="Stats_Multi_IdleCPU"/>
			<xs:enumeration value="Stats_Multi_SwapKB"/>
			<xs:enumeration value="Stats_Testing"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Stats4PerfSrvCfg">
		<xs:complexType>
			<xs:sequence maxOccurs="1" minOccurs="1">
				<xs:element maxOccurs="1" minOccurs="1" ref="Platform_configuration"/>
				<xs:element minOccurs="1" ref="StatsServer_Configuration"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="Platform_configuration">
		<xs:complexType>
			<xs:sequence maxOccurs="unbounded" minOccurs="1">
				<xs:element maxOccurs="unbounded" minOccurs="1" ref="node"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:NCName" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="node">
		<xs:complexType>
			<xs:sequence>
				<xs:element minOccurs="1" name="NodeIPAddress" type="IP"/>
				<xs:element minOccurs="1" name="SrvType" type="ServerType"/>
				<xs:element minOccurs="1" name="ClientPort" type="xs:integer"/>
			</xs:sequence>
			<xs:attribute name="name" type="xs:NCName" use="required"/>
			<xs:attribute name="enabled" type="xs:boolean" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="StatsServer_Configuration">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="StatsDatabase" type="xs:NCName"/>
				<xs:element name="StatsDatabaseType" type="xs:NCName"/>
				<xs:element name="StatsCollect" type="xs:NCName"/>
				<xs:element name="SavedDays" type="xs:integer"/>
				<xs:element name="StatsIpAddress" type="IP"/>
				<xs:element name="StatsPort" type="xs:integer"/>
				<xs:element name="StatsTypeDef">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded" minOccurs="1">
							<xs:element name="StatsType">
								<xs:complexType>
									<xs:sequence maxOccurs="unbounded" minOccurs="1">
										<xs:element name="StatsNode" type="xs:string"/>
									</xs:sequence>
									<xs:attribute name="type" type="AnalyzeType" use="required"/>
									<xs:attribute name="stat" type="StatType" use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="enabled" type="xs:boolean" use="required"/>
			<xs:attribute name="Monitoring" type="xs:boolean" use="required"/>
			<xs:attribute name="name" type="xs:NCName" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== owlytest/OwlyServer/OwlySrv/src/main/resources/properties/OwlySrv.xml
<?xml version="1.0" encoding="UTF-8"?>
<Stats4PerfSrvCfg xsi:noNamespaceSchemaLocation="OwlySrv.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<Platform_configuration name="MCM_Platform_HA">
	<!--  
	Platform Definition where LoadTests are executed 	
	Type of Server is : LoadServer,AdminServer,SubsServer,JMSServer, and DatabaseServer
	
	<node name="adm1">  Name used in configuration to refer this server.
		<NodeIPAddress>135.248.3.78</NodeIPAddress>  IP of this server
		<SrvType>AdminServer</SrvType>  Type of server in the plaform ( LoadServer, AdminServer, SubsServer,JMSServer,DatabaseServer)
	</node>
	--> 

		<!-- <node name="as-adm-a" enabled="true">
			<NodeIPAddress>159.23.98.17</NodeIPAddress>
			<SrvType>AdminServer</SrvType>
			<ClientPort>5000</ClientPort>
		</node> -->
		<node name="owlysrv" enabled="true">
			<NodeIPAddress>127.0.0.1</NodeIPAddress>
			<SrvType>AdminServer</SrvType>
			<ClientPort>5000</ClientPort>
		</node>
		<!-- <node name="as-sub-a" enabled="true">
			<NodeIPAddress>159.23.99.100</NodeIPAddress>
			<SrvType>SubsServer</SrvType>
			<ClientPort>5000</ClientPort>
		</node> -->
	</Platform_configuration>
	<StatsServer_Configuration name="StatServer" enabled="true" Monitoring="false">
	<!--  
	Definition of the Stats Server to get metrics of the Stats  :
	StatsDatabase : DataBase name,
	StatsCollect : Is the Name of the Collect created ,
	Dates are dates used for automatic recollectionis executed only
	-->
		<StatsDatabase>OWLYSRV</StatsDatabase>
		<StatsDatabaseType>MONGODB</StatsDatabaseType>
		<StatsCollect>PerformanceTests</StatsCollect>
		<SavedDays>5</SavedDays>
		<StatsIpAddress>127.0.0.1</StatsIpAddress>
		<StatsPort>27017</StatsPort>
		<StatsTypeDef>
		<!--  
		Definition of reports we want to get from Dimitrik,
			Reports have been previously created in DImStat as BookMarks.
			Two kind of reports can be executed : SingleHost or MultiHost, refer 
			DImStat Documentation for this	
		--> 
			<StatsType stat="Stats_Vmstat" type="SingleHost">
				<StatsNode>owlysrv</StatsNode>
				<!-- <StatsNode>as-adm-b</StatsNode>
				<StatsNode>as-sub-a</StatsNode> -->
			</StatsType>
			<StatsType stat="Stats_TopCPU" type="SingleHost">
				<StatsNode>owlysrv</StatsNode>
				<!-- <StatsNode>as-adm-b</StatsNode>
				<StatsNode>as-sub-a</StatsNode> -->
			</StatsType>
		</StatsTypeDef>
	</StatsServer_Configuration>
	
</Stats4PerfSrvCfg>
